# -*- coding: utf-8 -*-
"""Bengali_newspaper_word2vec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G8yGdckInyuC-PkHcM9G8xRpsBPF-pMT

Download from Kaggle
"""

!pip install kaggle

"""Then you'll need a Kaggle API token (kaggle.json) — if you don't have one:

Go to kaggle.com → your account settings → "Create New API Token" (downloads kaggle.json)
Upload that file to Colab:

save the token
"""

!mkdir -p ~/.kaggle && echo KGAT_2cd8456cee7b1aa04fa471aa471b1ee9 > ~/.kaggle/access_token && chmod 600 ~/.kaggle/access_token

"""Install the Kaggle tool"""

!pip install kaggle

"""Download the Prothom Alo dataset"""

!kaggle datasets download -d ishfar/prothom-alo-news-articles

"""Unzip it"""

!unzip prothom-alo-news-articles.zip -d prothom_alo_data



"""Check what's inside"""

!ls -lh prothom_alo_data

"""giving us a sense of the date range covered"""

!ls prothom_alo_data/csv | wc -l

"""let's check the actual structure of one file."""

import pandas as pd
df = pd.read_csv("prothom_alo_data/csv/2009-07.csv")
print(df.shape)
print(df.columns.tolist())
df.head(3)



"""combine all 141 files into corpus"""

import pandas as pd
import glob
import re

def clean_newspaper_text(text):
    if pd.isna(text):
        return ""
    text = re.sub(r'\s+', ' ', str(text))  # normalize whitespace
    return text.strip()

csv_files = sorted(glob.glob("prothom_alo_data/csv/*.csv"))
print(f"Found {len(csv_files)} monthly files")

count = 0
with open("bengali_newspaper_corpus.txt", "w", encoding="utf-8") as f_out:
    for filepath in csv_files:
        try:
            df = pd.read_csv(filepath)
            for _, row in df.iterrows():
                if row.get('status') == 'published':
                    body = clean_newspaper_text(row.get('body'))
                    if len(body) > 20:
                        f_out.write(body + "\n")
                        count += 1
        except Exception as e:
            print(f"Error in {filepath}: {e}")

print(f"\nTotal articles written: {count}")

"""Check the file size"""

!ls -lh bengali_newspaper_corpus.txt

"""Save to a new, dedicated Drive folder"""

from google.colab import drive
drive.mount('/content/drive')

import os
DRIVE_DIR = "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project"
os.makedirs(DRIVE_DIR, exist_ok=True)

!cp bengali_newspaper_corpus.txt "{DRIVE_DIR}/"
print("Saved to Drive.")

"""Run this first — it processes the file line-by-line without holding everything in memory at once, writing a pre-tokenized version to disk.

Then train using streaming input (also memory-efficient, doesn't load everything into RAM):

In short: we took your raw newspaper corpus file (4.6GB of full sentences) and converted it into a pre-tokenized version — breaking every sentence into individual words (removing punctuation) — and saved that as a new file, processing it one line at a time instead of loading everything into memory at once.

Why this mattered specifically for this large corpus: Your earlier approach (used for Wikipedia and Literature) loaded every tokenized sentence into one big Python list (sentences = []) before training — fine for smaller corpora, but risky for a 4.6GB file, since it could exhaust Colab's available memory. This time, we wrote the tokenized words straight to a new file on disk instead of keeping them all in RAM, avoiding that risk.

What's in bengali_newspaper_tokenized.txt now: the same content as your original corpus, just with punctuation stripped and each sentence's words separated by spaces — ready for the next step, where Word2Vec will read this file directly from disk, one line at a time, rather than needing it all loaded in memory first.
"""

!pip install gensim

from gensim.models import Word2Vec
from gensim.models.word2vec import LineSentence
import re

# First, create a pre-tokenized version of the file (streamed, memory-efficient)
def tokenize(text):
    text = re.sub(r'[।,.!?"()\[\]—\-\'‘’]', ' ', text)
    return text.split()

with open("bengali_newspaper_corpus.txt", encoding="utf-8") as f_in, \
     open("bengali_newspaper_tokenized.txt", "w", encoding="utf-8") as f_out:
    for line in f_in:
        tokens = tokenize(line)
        if tokens:
            f_out.write(" ".join(tokens) + "\n")

print("Tokenized file created.")

"""train the model using this tokenized file"""

!pip install gensim

# 1. Get your corpus file back (from Drive if saved, otherwise re-extract from the CSVs)
!ls -lh "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project/"

from google.colab import drive
drive.mount('/content/drive')

!ls -lh "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project/"

"""Step 1: Copy the corpus back from Drive"""

!cp "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project/bengali_newspaper_corpus.txt" .
!ls -lh bengali_newspaper_corpus.txt

"""Split the corpus into chunks of 240,000 lines each"""

!split -l 240000 bengali_newspaper_corpus.txt bengali_chunk_ --numeric-suffixes=1 --additional-suffix=.txt
!ls -lh bengali_chunk_*.txt

"""Tokenize each chunk separately (memory-safe, one chunk at a time)"""

import re, glob

def tokenize(text):
    text = re.sub(r'[।,.!?"()\[\]—\-\'‘’]', ' ', text)
    return text.split()

chunk_files = sorted(glob.glob("bengali_chunk_*.txt"))
print(f"Found {len(chunk_files)} chunks")

for chunk_file in chunk_files:
    out_file = chunk_file.replace(".txt", "_tokenized.txt")
    with open(chunk_file, encoding="utf-8") as f_in, open(out_file, "w", encoding="utf-8") as f_out:
        for line in f_in:
            tokens = tokenize(line)
            if tokens:
                f_out.write(" ".join(tokens) + "\n")
    print(f"Tokenized: {out_file}")

"""Incremental training — one chunk at a time, checkpointing after each"""

import os, glob
from gensim.models import Word2Vec
from gensim.models.word2vec import LineSentence
from google.colab import drive

drive.mount('/content/drive')
DRIVE_DIR = "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project"
os.makedirs(DRIVE_DIR, exist_ok=True)

tokenized_chunks = sorted(glob.glob("bengali_chunk_*_tokenized.txt"))
checkpoint_path = f"{DRIVE_DIR}/bengali_newspaper_word2vec_progress.model"
progress_file = f"{DRIVE_DIR}/last_completed_chunk.txt"

# Check how far we've already gotten (resume support)
if os.path.exists(progress_file):
    with open(progress_file) as f:
        last_done = int(f.read().strip())
    print(f"Resuming — last completed chunk: {last_done}")
    model_news = Word2Vec.load(checkpoint_path)
else:
    last_done = 0
    model_news = None
    print("Starting fresh.")

for i, chunk_path in enumerate(tokenized_chunks, start=1):
    if i <= last_done:
        print(f"Skipping chunk {i} (already done)")
        continue

    print(f"\n--- Processing chunk {i}/{len(tokenized_chunks)}: {chunk_path} ---")
    sentences = LineSentence(chunk_path)

    if model_news is None:
        model_news = Word2Vec(vector_size=300, window=5, min_count=5, workers=2, sg=1, epochs=5)
        model_news.build_vocab(sentences)
    else:
        model_news.build_vocab(sentences, update=True)

    model_news.train(sentences, total_examples=model_news.corpus_count, epochs=model_news.epochs)

    model_news.save(checkpoint_path)
    with open(progress_file, "w") as f:
        f.write(str(i))

    print(f"✅ Chunk {i} done and saved.")

model_news.save(f"{DRIVE_DIR}/bengali_newspaper_word2vec_FINAL.model")
print("\n🎉 All chunks processed. Final model saved.")

!pip install gensim

from google.colab import drive
drive.mount('/content/drive')

!ls -lh "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project/"

"""Copy your corpus back"""

!cp "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project/bengali_newspaper_corpus.txt" .

"""Re-split into chunks"""

!split -l 240000 bengali_newspaper_corpus.txt bengali_chunk_ --numeric-suffixes=1 --additional-suffix=.txt

"""Re-tokenize all chunks"""

import re, glob

def tokenize(text):
    text = re.sub(r'[।,.!?"()\[\]—\-\'‘’]', ' ', text)
    return text.split()

chunk_files = sorted(glob.glob("bengali_chunk_*.txt"))
for chunk_file in chunk_files:
    out_file = chunk_file.replace(".txt", "_tokenized.txt")
    with open(chunk_file, encoding="utf-8") as f_in, open(out_file, "w", encoding="utf-8") as f_out:
        for line in f_in:
            tokens = tokenize(line)
            if tokens:
                f_out.write(" ".join(tokens) + "\n")
    print(f"Tokenized: {out_file}")

"""Run training — this will now correctly detect chunk 1 is done and resume at chunk 2"""

import os, glob
from gensim.models import Word2Vec
from gensim.models.word2vec import LineSentence

DRIVE_DIR = "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project"
tokenized_chunks = sorted(glob.glob("bengali_chunk_*_tokenized.txt"))
checkpoint_path = f"{DRIVE_DIR}/bengali_newspaper_word2vec_progress.model"
progress_file = f"{DRIVE_DIR}/last_completed_chunk.txt"

with open(progress_file) as f:
    last_done = int(f.read().strip())
print(f"Resuming — last completed chunk: {last_done}")
model_news = Word2Vec.load(checkpoint_path)

for i, chunk_path in enumerate(tokenized_chunks, start=1):
    if i <= last_done:
        print(f"Skipping chunk {i} (already done)")
        continue

    print(f"\n--- Processing chunk {i}/{len(tokenized_chunks)}: {chunk_path} ---")
    sentences = LineSentence(chunk_path)
    model_news.build_vocab(sentences, update=True)
    model_news.train(sentences, total_examples=model_news.corpus_count, epochs=model_news.epochs)

    model_news.save(checkpoint_path)
    with open(progress_file, "w") as f:
        f.write(str(i))
    print(f"✅ Chunk {i} done and saved.")

model_news.save(f"{DRIVE_DIR}/bengali_newspaper_word2vec_FINAL.model")
print("\n🎉 All chunks processed. Final model saved.")

!pip install gensim
from google.colab import drive
drive.mount('/content/drive')

!ls -lh "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project/"
!cat "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project/last_completed_chunk.txt"

!cp "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project/bengali_newspaper_corpus.txt" .

!tail -n +240001 bengali_newspaper_corpus.txt > remaining_corpus.txt
!wc -l remaining_corpus.txt

!split -l 60000 remaining_corpus.txt bengali_small_chunk_ --numeric-suffixes=1 --additional-suffix=.txt
!ls bengali_small_chunk_*.txt | wc -l

import re, glob

def tokenize(text):
    text = re.sub(r'[।,.!?"()\[\]—\-\'‘’]', ' ', text)
    return text.split()

chunk_files = sorted(glob.glob("bengali_small_chunk_*.txt"))
for chunk_file in chunk_files:
    out_file = chunk_file.replace(".txt", "_tokenized.txt")
    with open(chunk_file, encoding="utf-8") as f_in, open(out_file, "w", encoding="utf-8") as f_out:
        for line in f_in:
            tokens = tokenize(line)
            if tokens:
                f_out.write(" ".join(tokens) + "\n")
    print(f"Tokenized: {out_file}")

import os, glob, time
from gensim.models import Word2Vec
from gensim.models.word2vec import LineSentence

DRIVE_DIR = "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project"
checkpoint_path = f"{DRIVE_DIR}/bengali_newspaper_word2vec_progress.model"
small_progress_file = f"{DRIVE_DIR}/last_completed_small_chunk.txt"

model_news = Word2Vec.load(checkpoint_path)

if os.path.exists(small_progress_file):
    with open(small_progress_file) as f:
        last_done = int(f.read().strip())
else:
    last_done = 0
print(f"Resuming small chunks from: {last_done}")

small_chunks = sorted(glob.glob("bengali_small_chunk_*_tokenized.txt"))
total_chunks = len(small_chunks)
chunk_times = []

overall_start = time.time()

for i, chunk_path in enumerate(small_chunks, start=1):
    if i <= last_done:
        print(f"Skipping small chunk {i} (already done)")
        continue

    chunk_start = time.time()
    print(f"\n--- Small chunk {i}/{total_chunks}: {chunk_path} ---")
    print(f"⏱️  Started at: {time.strftime('%H:%M:%S')}")

    sentences = LineSentence(chunk_path)
    model_news.build_vocab(sentences, update=True)
    model_news.train(sentences, total_examples=model_news.corpus_count, epochs=model_news.epochs)

    model_news.save(checkpoint_path)
    with open(small_progress_file, "w") as f:
        f.write(str(i))

    chunk_elapsed = time.time() - chunk_start
    chunk_times.append(chunk_elapsed)
    avg_time = sum(chunk_times) / len(chunk_times)
    remaining_chunks = total_chunks - i
    est_remaining = avg_time * remaining_chunks

    print(f"✅ Small chunk {i} done and saved.")
    print(f"⏱️  This chunk took: {chunk_elapsed/60:.1f} min")
    print(f"📊 Average per chunk: {avg_time/60:.1f} min")
    print(f"⏳ Estimated remaining: {est_remaining/60:.1f} min ({est_remaining/3600:.1f} hours) for {remaining_chunks} chunks left")
    print(f"📈 Progress: {i}/{total_chunks} ({i/total_chunks*100:.0f}%)")

total_elapsed = time.time() - overall_start
print(f"\n🎉 All small chunks processed in this session: {total_elapsed/60:.1f} min")
model_news.save(f"{DRIVE_DIR}/bengali_newspaper_word2vec_FINAL.model")
print("Final model saved.")

!ls -lh "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project/"

"""let's load it"""

from gensim.models import Word2Vec

DRIVE_DIR = "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project"
model_news = Word2Vec.load(f"{DRIVE_DIR}/bengali_newspaper_word2vec_FINAL.model")
print("Model loaded successfully.")
print(f"Vocabulary size: {len(model_news.wv)}")

"""run the word-frequency counting step"""

import re
from collections import Counter
import pickle

def tokenize(text):
    text = re.sub(r'[।,.!?"()\[\]—\-\'‘’]', ' ', text)
    return text.split()

word_counts_news = Counter()
with open("bengali_newspaper_corpus.txt", encoding="utf-8") as f:
    for line in f:
        word_counts_news.update(tokenize(line))

with open(f"{DRIVE_DIR}/word_counts_newspaper.pkl", "wb") as f:
    pickle.dump(word_counts_news, f)

test_words = ["নারী", "পুরুষ", "মা", "বাবা", "রাজা", "রানী"]
for w in test_words:
    print(f"{w}: {word_counts_news[w]}")

"""build the gender direction"""

import numpy as np
from sklearn.decomposition import PCA

defining_pairs_news = [
    ("নারী", "পুরুষ"), ("কন্যা", "পুত্র"), ("মা", "বাবা"),
    ("মেয়ে", "ছেলে"), ("রানী", "রাজা"), ("স্ত্রী", "স্বামী"),
    ("ম্যাডাম", "স্যার"),
]

diffs_news = []
for f_word, m_word in defining_pairs_news:
    if f_word in model_news.wv and m_word in model_news.wv:
        diffs_news.append(model_news.wv[f_word] - model_news.wv[m_word])
        print(f"{f_word} - {m_word}: OK")
    else:
        print(f"{f_word} - {m_word}: MISSING")

diffs_news = np.array(diffs_news)
pca_news = PCA(n_components=min(len(diffs_news), 10))
pca_news.fit(diffs_news)
gender_direction_news = pca_news.components_[0]
gap_news = pca_news.explained_variance_ratio_[0] - pca_news.explained_variance_ratio_[1]

np.save(f"{DRIVE_DIR}/gender_direction_newspaper.npy", gender_direction_news)
print(f"\nNewspaper gender direction computed. PCA gap: {gap_news:.3f}")

"""Load the trained model first"""

from google.colab import drive
drive.mount('/content/drive')

!pip install gensim
from gensim.models import Word2Vec
import numpy as np

DRIVE_DIR = "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project"
model_news = Word2Vec.load(f"{DRIVE_DIR}/bengali_newspaper_word2vec_FINAL.model")
gender_direction_news = np.load(f"{DRIVE_DIR}/gender_direction_newspaper.npy")

def cosine_sim(vec1, vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

def direct_bias(word, gender_direction, model, c=1):
    if word not in model.wv:
        return None
    vec = model.wv[word]
    cos_sim = cosine_sim(vec, gender_direction)
    return abs(cos_sim) ** c * np.sign(cos_sim)

print("Reloaded successfully.")

"""single word"""

single_words_news = {
    "scientist": "বিজ্ঞানী",
    "musician": "সঙ্গীতশিল্পী",
    "artist": "শিল্পী",
    "judge": "বিচারক",
    "inventor": "উদ্ভাবক",
    "soldier": "সৈনিক",
    "journalist": "সাংবাদিক",
    "athlete": "ক্রীড়াবিদ",
    "farmer": "কৃষক",
    "lawyer": "আইনজীবী",
    "adventurer": "অভিযাত্রী",
    "aide": "সহকারী",
    "ambassador": "রাষ্ট্রদূত",
    "analyst": "বিশ্লেষক",
    "astronaut": "নভোচারী",
    "astronomer": "জ্যোতির্বিজ্ঞানী",
    "biologist": "জীববিজ্ঞানী",
    "banker": "ব্যাংকার",
}

print("=== Bengali Newspaper: Single-form profession words (full 18-word set) ===")
results_single_news = {}
for label, word in single_words_news.items():
    bias = direct_bias(word, gender_direction_news, model_news)
    if bias is not None:
        results_single_news[label] = float(bias)
        direction = "Female-leaning" if bias > 0 else "Male-leaning"
        print(f"{label:15s} {word:15s} bias: {bias:+.4f}  ({direction})")
    else:
        print(f"{label:15s} {word:15s} NOT FOUND in vocabulary")

"""borrowed/native and gendered pairs"""

borrowed_native_pairs_news = {
    "engineer": [("ইঞ্জিনিয়ার", 0), ("প্রকৌশলী", 0)],
    "manager": [("ম্যানেজার", 0), ("ব্যবস্থাপক", 0)],
    "driver": [("ড্রাইভার", 0), ("চালক", 0)],
    "chef": [("শেফ", 0), ("রাঁধুনি", 0)],
    "governor": [("গভর্নর", 0), ("রাজ্যপাল", 0)],
    "worker": [("শ্রমিক", 0), ("কর্মী", 0)],
    "person": [("ব্যক্তি", 0), ("মানুষ", 0)],
}

for label, forms in borrowed_native_pairs_news.items():
    borrowed_native_pairs_news[label] = [(w, word_counts_news[w]) for w, _ in forms]

print("=== Bengali Newspaper: Borrowed/Native pairs ===")
results_dual_news = {}
for label, forms in borrowed_native_pairs_news.items():
    total_count = sum(count for _, count in forms)
    if total_count == 0:
        print(f"{label:12s} SKIPPED — zero total count")
        continue
    weighted_bias = 0
    detail = []
    for word, count in forms:
        bias = direct_bias(word, gender_direction_news, model_news)
        if bias is not None:
            weighted_bias += bias * (count / total_count)
            detail.append(f"{word}({count})={bias:+.4f}")
    results_dual_news[label] = float(weighted_bias)
    print(f"{label:12s} weighted bias: {weighted_bias:+.4f}   [{', '.join(detail)}]")

"""gendered pairs"""

gendered_pairs_news = {
    "teacher": [("শিক্ষক", word_counts_news["শিক্ষক"]), ("শিক্ষিকা", word_counts_news["শিক্ষিকা"])],
    "actor": [("অভিনেতা", word_counts_news["অভিনেতা"]), ("অভিনেত্রী", word_counts_news["অভিনেত্রী"])],
    "writer": [("লেখক", word_counts_news["লেখক"]), ("লেখিকা", word_counts_news["লেখিকা"])],
    "nurse": [("নার্স", word_counts_news["নার্স"]), ("সেবিকা", word_counts_news["সেবিকা"])],
    "student": [("ছাত্র", word_counts_news["ছাত্র"]), ("ছাত্রী", word_counts_news["ছাত্রী"]), ("শিক্ষার্থী", word_counts_news["শিক্ষার্থী"])],
}

print("=== Bengali Newspaper: Gendered pairs ===")
results_gendered_news = {}
for label, forms in gendered_pairs_news.items():
    total_count = sum(count for _, count in forms)
    if total_count == 0:
        print(f"{label:12s} SKIPPED — zero total count")
        continue
    weighted_bias = 0
    detail = []
    for word, count in forms:
        bias = direct_bias(word, gender_direction_news, model_news)
        if bias is not None:
            weighted_bias += bias * (count / total_count)
            detail.append(f"{word}({count})={bias:+.4f}")
    results_gendered_news[label] = float(weighted_bias)
    print(f"{label:12s} weighted bias: {weighted_bias:+.4f}   [{', '.join(detail)}]")

"""multi-word phrases"""

from gensim.models import Word2Vec
import numpy as np

DRIVE_DIR = "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project"

model_news = Word2Vec.load(f"{DRIVE_DIR}/bengali_newspaper_word2vec_FINAL.model")
gender_direction_news = np.load(f"{DRIVE_DIR}/gender_direction_newspaper.npy")

print("Model and gender direction loaded successfully.")

"""defines all three functions together,"""

import numpy as np

def cosine_sim(vec1, vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

def multiword_vector(phrase_words, model):
    vecs = [model.wv[w] for w in phrase_words if w in model.wv]
    if not vecs:
        return None
    return np.mean(vecs, axis=0)

def direct_bias_vec(vec, gender_direction, c=1):
    cos_sim = cosine_sim(vec, gender_direction)
    return abs(cos_sim) ** c * np.sign(cos_sim)

from gensim.models import Word2Vec
import numpy as np

DRIVE_DIR = "/content/drive/MyDrive/Bengali_Newspaper_NLP_Bias_Project"
model_news = Word2Vec.load(f"{DRIVE_DIR}/bengali_newspaper_word2vec_FINAL.model")
gender_direction_news = np.load(f"{DRIVE_DIR}/gender_direction_newspaper.npy")

def cosine_sim(vec1, vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))
def multiword_vector(phrase_words, model):
    vecs = [model.wv[w] for w in phrase_words if w in model.wv]
    if not vecs:
        return None
    return np.mean(vecs, axis=0)
def direct_bias_vec(vec, gender_direction, c=1):
    cos_sim = cosine_sim(vec, gender_direction)
    return abs(cos_sim) ** c * np.sign(cos_sim)

def count_phrase_streaming(filepath, phrase):
    count = 0
    with open(filepath, encoding="utf-8") as f:
        for line in f:
            count += line.count(phrase)
    return count

count_m_news = count_phrase_streaming("bengali_newspaper_corpus.txt", "কৌতুক অভিনেতা")
count_f_news = count_phrase_streaming("bengali_newspaper_corpus.txt", "কৌতুক অভিনেত্রী")

print(f"comedian(M) count: {count_m_news}")
print(f"comedian(F) count: {count_f_news}")

comedian_m_vec_news = multiword_vector(["কৌতুক", "অভিনেতা"], model_news)
comedian_f_vec_news = multiword_vector(["কৌতুক", "অভিনেত্রী"], model_news)
if comedian_m_vec_news is not None and comedian_f_vec_news is not None:
    bias_m_news = float(direct_bias_vec(comedian_m_vec_news, gender_direction_news))
    bias_f_news = float(direct_bias_vec(comedian_f_vec_news, gender_direction_news))
    total_news = count_m_news + count_f_news
    if total_news > 0:
        weighted_comedian_news = (bias_m_news * count_m_news + bias_f_news * count_f_news) / total_news
        print(f"comedian: {weighted_comedian_news:+.4f}")
    else:
        print("comedian: phrase not found in corpus at all")

filmmaker_vec_news = multiword_vector(["চলচ্চিত্র", "নির্মাতা"], model_news)
if filmmaker_vec_news is not None:
    bias_filmmaker_news = float(direct_bias_vec(filmmaker_vec_news, gender_direction_news))
    print(f"filmmaker: {bias_filmmaker_news:+.4f}")

def cosine_sim(vec1, vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

def direct_bias(word, gender_direction, model, c=1):
    if word not in model.wv:
        return None
    vec = model.wv[word]
    cos_sim = cosine_sim(vec, gender_direction)
    return abs(cos_sim) ** c * np.sign(cos_sim)



missing_words_news = {
    "judge": "বিচারক",
    "farmer": "কৃষক",
    "adventurer": "অভিযাত্রী",
    "aide": "সহকারী",
    "astronomer": "জ্যোতির্বিজ্ঞানী",
    "astronaut": "নভোচারী",
}

print("=== Bengali Newspaper: Previously Missing Single Words ===")
results_missing_news = {}
for label, word in missing_words_news.items():
    bias = direct_bias(word, gender_direction_news, model_news)
    if bias is not None:
        results_missing_news[label] = float(bias)
        direction = "Female-leaning" if bias > 0 else "Male-leaning"
        print(f"{label:15s} {word:15s} bias: {bias:+.4f}  ({direction})")
    else:
        print(f"{label:15s} {word:15s} NOT FOUND in vocabulary")



"""32 professions for the newspaper corpus"""

results_single_news = {
    "scientist": 0.0549, "musician": -0.0027, "artist": 0.0185,
    "inventor": 0.0851, "soldier": 0.0359, "journalist": 0.0117,
    "athlete": -0.0380, "ambassador": 0.1314, "analyst": 0.0235,
    "lawyer": -0.0643, "banker": -0.0726, "biologist": 0.0632,
}

results_dual_news = {
    "engineer": -0.0906, "manager": -0.1048, "driver": -0.0915,
    "chef": -0.0052, "governor": 0.0651, "worker": -0.1009,
    "person": 0.0530,
}

results_gendered_news = {
    "teacher": -0.1447, "actor": -0.0510, "writer": 0.0216,
    "nurse": -0.1820, "student": -0.0486,
}

all_results_news = {}
all_results_news.update(results_single_news)
all_results_news.update(results_dual_news)
all_results_news.update(results_gendered_news)
all_results_news["comedian"] = 0.0016
all_results_news["filmmaker"] = -0.0336

print(f"Total professions with data: {len(all_results_news)} out of 32")
print("\n=== Bengali Newspaper: All Bias Scores ===")
for label, bias in sorted(all_results_news.items(), key=lambda x: x[1]):
    direction = "Female" if bias > 0 else "Male"
    print(f"{label:15s} {bias:+.4f}  ({direction})")

simple_avg_news = sum(all_results_news.values()) / len(all_results_news)
print(f"\nSimple average: {simple_avg_news:+.4f}")

import json
with open(f"{DRIVE_DIR}/bias_scores_newspaper.json", "w", encoding="utf-8") as f:
    json.dump(all_results_news, f, ensure_ascii=False, indent=2)
print("Saved to Drive.")

all_results_news = {}
all_results_news.update(results_single_news)
all_results_news.update(results_dual_news)
all_results_news.update(results_gendered_news)
all_results_news.update(results_missing_news)
all_results_news["comedian"] = 0.0016
all_results_news["filmmaker"] = -0.0336

print(f"Total professions with data: {len(all_results_news)} out of 32")
print("\n=== Bengali Newspaper: COMPLETE Bias Scores (All 32) ===")
for label, bias in sorted(all_results_news.items(), key=lambda x: x[1]):
    direction = "Female" if bias > 0 else "Male"
    print(f"{label:15s} {bias:+.4f}  ({direction})")

simple_avg_news = sum(all_results_news.values()) / len(all_results_news)
print(f"\nSimple average (all 32): {simple_avg_news:+.4f}")

import json
with open(f"{DRIVE_DIR}/bias_scores_newspaper.json", "w", encoding="utf-8") as f:
    json.dump(all_results_news, f, ensure_ascii=False, indent=2)
print("Saved to Drive.")

"""weighted bias"""

import pickle

with open(f"{DRIVE_DIR}/word_counts_newspaper.pkl", "rb") as f:
    word_counts_news = pickle.load(f)

print("Word counts reloaded successfully.")
print(f"নারী: {word_counts_news['নারী']}")  # quick sanity check


profession_word_map_news = {
    "scientist": ["বিজ্ঞানী"], "musician": ["সঙ্গীতশিল্পী"], "artist": ["শিল্পী"],
    "inventor": ["উদ্ভাবক"], "soldier": ["সৈনিক"], "journalist": ["সাংবাদিক"],
    "athlete": ["ক্রীড়াবিদ"], "ambassador": ["রাষ্ট্রদূত"], "analyst": ["বিশ্লেষক"],
    "lawyer": ["আইনজীবী"], "banker": ["ব্যাংকার"], "biologist": ["জীববিজ্ঞানী"],
    "engineer": ["ইঞ্জিনিয়ার", "প্রকৌশলী"], "manager": ["ম্যানেজার", "ব্যবস্থাপক"],
    "driver": ["ড্রাইভার", "চালক"], "chef": ["শেফ", "রাঁধুনি"],
    "governor": ["গভর্নর", "রাজ্যপাল"], "worker": ["শ্রমিক", "কর্মী"],
    "person": ["ব্যক্তি", "মানুষ"], "teacher": ["শিক্ষক", "শিক্ষিকা"],
    "actor": ["অভিনেতা", "অভিনেত্রী"], "writer": ["লেখক", "লেখিকা"],
    "nurse": ["নার্স", "সেবিকা"], "student": ["ছাত্র", "ছাত্রী", "শিক্ষার্থী"],
    "judge": ["বিচারক"], "farmer": ["কৃষক"], "adventurer": ["অভিযাত্রী"],
    "aide": ["সহকারী"], "astronomer": ["জ্যোতির্বিজ্ঞানী"], "astronaut": ["নভোচারী"],
}

profession_counts_news = {label: sum(word_counts_news[w] for w in words) for label, words in profession_word_map_news.items()}
profession_counts_news["filmmaker"] = count_phrase_streaming("bengali_newspaper_corpus.txt", "চলচ্চিত্র নির্মাতা")
profession_counts_news["comedian"] = count_m_news + count_f_news

total_weight = sum(profession_counts_news[label] for label in all_results_news.keys())
weighted_avg_news = sum(all_results_news[label] * profession_counts_news[label] for label in all_results_news.keys()) / total_weight

print(f"Weighted average: {weighted_avg_news:+.4f}")

!find "/content/drive/MyDrive/" -iname "*prothom*" 2>/dev/null

"""Reload literature corpus. again"""

from google.colab import drive
drive.mount('/content/drive')

"""Copy the file back from Drive to your local working directory"""

!cp "/content/drive/MyDrive/Bengali_Literature_NLP_Bias_Project/bengali_literature_corpus_v2.txt" .

"""Verify it copied successfully"""

!ls -lh bengali_literature_corpus_v2.txt

"""sample random chunks and actually read them"""

import random

with open("bengali_literature_corpus_v2.txt", encoding="utf-8") as f:
    lines = f.readlines()

print(f"Total lines: {len(lines)}")

random.seed(42)
sample_indices = random.sample(range(len(lines)), 20)
for i in sample_indices:
    print(f"\n--- Line {i} ---")
    print(lines[i][:300])