# -*- coding: utf-8 -*-
"""Bengali_literature_word2vec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ST7MoSPUJy9rndEUURN9N3hd1IQsAWW_

Download the larger, full-namespace dump
"""

!wget https://dumps.wikimedia.org/bnwikisource/latest/bnwikisource-latest-pages-meta-current.xml.bz2

!bzcat bnwikisource-latest-pages-meta-current.xml.bz2 | grep -m 5 '<ns>104</ns>'

"""Inspect one real Page: entry first, so we know exactly what to clean"""

import bz2

count = 0
with bz2.open("bnwikisource-latest-pages-meta-current.xml.bz2", "rt", encoding="utf-8") as f:
    inside_ns104_page = False
    buffer = []
    for line in f:
        if "<ns>104</ns>" in line:
            inside_ns104_page = True
        if inside_ns104_page:
            buffer.append(line)
        if "</page>" in line and inside_ns104_page:
            count += 1
            if count == 3:  # print the 3rd example we find
                print("".join(buffer))
                break
            buffer = []
            inside_ns104_page = False

import bz2
import re

def clean_wikisource_text(raw_text):
    if raw_text is None:
        return ""
    text = re.sub(r'<noinclude>.*?</noinclude>', '', raw_text, flags=re.DOTALL)
    text = re.sub(r'<pagequality[^/]*/>', '', text)
    text = re.sub(r"'''?", '', text)
    text = re.sub(r'\{\{[^}]*\}\}', '', text)
    text = re.sub(r'\[\[(File|Image|চিত্র):[^\]]*\]\]', '', text)
    text = re.sub(r'\[\[([^\]|]*\|)?([^\]]*)\]\]', r'\2', text)
    text = re.sub(r'<[^>]+>', '', text)
    return text.strip()

def get_quality_level(raw_text):
    match = re.search(r'pagequality level="(\d)"', raw_text)
    if match:
        return int(match.group(1))
    return None

count_total = 0
count_kept = 0
quality_counts = {}

with bz2.open("bnwikisource-latest-pages-meta-current.xml.bz2", "rt", encoding="utf-8") as f_in, \
     open("bengali_literature_corpus_v2.txt", "w", encoding="utf-8") as f_out:

    in_page = False
    in_ns104 = False
    in_text = False
    current_text = []

    for line in f_in:
        if "<page>" in line:
            in_page = True
            in_ns104 = False
            current_text = []
        if in_page and "<ns>104</ns>" in line:
            in_ns104 = True
        if in_page and in_ns104 and "<text" in line:
            in_text = True
        if in_text:
            current_text.append(line)
        if in_text and "</text>" in line:
            in_text = False
            raw = "".join(current_text)
            match = re.search(r'<text[^>]*>(.*)</text>', raw, re.DOTALL)
            if match:
                count_total += 1
                raw_content = match.group(1)
                quality = get_quality_level(raw_content)
                quality_counts[quality] = quality_counts.get(quality, 0) + 1

                if quality is not None and quality >= 3:
                    cleaned = clean_wikisource_text(raw_content)
                    if len(cleaned) > 20:
                        f_out.write(cleaned + "\n")
                        count_kept += 1
        if "</page>" in line:
            in_page = False
            in_ns104 = False

print(f"Total Page: namespace entries found: {count_total}")
print(f"Kept (quality >= 3): {count_kept}")
print(f"Quality level breakdown: {quality_counts}")

"""unescape the HTML entities first, before running any regex checks."""

import bz2
import re
import html

def clean_wikisource_text(raw_text):
    if raw_text is None:
        return ""
    text = html.unescape(raw_text)  # convert &lt; &gt; &quot; etc. back to real characters
    text = re.sub(r'<noinclude>.*?</noinclude>', '', text, flags=re.DOTALL)
    text = re.sub(r'<pagequality[^/]*/>', '', text)
    text = re.sub(r"'''?", '', text)
    text = re.sub(r'\{\{[^}]*\}\}', '', text)
    text = re.sub(r'\[\[(File|Image|চিত্র):[^\]]*\]\]', '', text)
    text = re.sub(r'\[\[([^\]|]*\|)?([^\]]*)\]\]', r'\2', text)
    text = re.sub(r'<[^>]+>', '', text)
    return text.strip()

def get_quality_level(raw_text):
    unescaped = html.unescape(raw_text)
    match = re.search(r'pagequality level="(\d)"', unescaped)
    if match:
        return int(match.group(1))
    return None

count_total = 0
count_kept = 0
quality_counts = {}

with bz2.open("bnwikisource-latest-pages-meta-current.xml.bz2", "rt", encoding="utf-8") as f_in, \
     open("bengali_literature_corpus_v2.txt", "w", encoding="utf-8") as f_out:

    in_page = False
    in_ns104 = False
    in_text = False
    current_text = []

    for line in f_in:
        if "<page>" in line:
            in_page = True
            in_ns104 = False
            current_text = []
        if in_page and "<ns>104</ns>" in line:
            in_ns104 = True
        if in_page and in_ns104 and "<text" in line:
            in_text = True
        if in_text:
            current_text.append(line)
        if in_text and "</text>" in line:
            in_text = False
            raw = "".join(current_text)
            match = re.search(r'<text[^>]*>(.*)</text>', raw, re.DOTALL)
            if match:
                count_total += 1
                raw_content = match.group(1)
                quality = get_quality_level(raw_content)
                quality_counts[quality] = quality_counts.get(quality, 0) + 1

                if quality is not None and quality >= 3:
                    cleaned = clean_wikisource_text(raw_content)
                    if len(cleaned) > 20:
                        f_out.write(cleaned + "\n")
                        count_kept += 1
        if "</page>" in line:
            in_page = False
            in_ns104 = False

print(f"Total Page: namespace entries found: {count_total}")
print(f"Kept (quality >= 3): {count_kept}")
print(f"Quality level breakdown: {quality_counts}")

!ls -lh bengali_literature_corpus_v2.txt

"""Save to your Bengali Literature Drive folder"""

from google.colab import drive
drive.mount('/content/drive')

import os
DRIVE_DIR = "/content/drive/MyDrive/Bengali_Literature_NLP_Bias_Project"
os.makedirs(DRIVE_DIR, exist_ok=True)

!cp bengali_literature_corpus_v2.txt "{DRIVE_DIR}/"
print("Saved to Drive.")

"""Tokenize and train Word2Vec"""

!pip install gensim
from gensim.models import Word2Vec
import re

def tokenize(text):
    text = re.sub(r'[।,.!?"()\[\]—\-\'‘’]', ' ', text)
    return text.split()

sentences = []
with open("bengali_literature_corpus_v2.txt", encoding="utf-8") as f:
    for line in f:
        tokens = tokenize(line)
        if tokens:
            sentences.append(tokens)

print(f"Total sentences: {len(sentences)}")

model = Word2Vec(sentences, vector_size=300, window=5, min_count=5, workers=4, sg=1)
model.save(f"{DRIVE_DIR}/bengali_literature_word2vec.model")
print("Model trained and saved.")

from collections import Counter
import pickle

word_counts_lit = Counter()
with open("bengali_literature_corpus_v2.txt", encoding="utf-8") as f:
    for line in f:
        word_counts_lit.update(tokenize(line))

with open(f"{DRIVE_DIR}/word_counts_literature.pkl", "wb") as f:
    pickle.dump(word_counts_lit, f)

# Quick sanity check on key words
test_words = ["নারী", "পুরুষ", "মা", "বাবা", "রাজা", "রানী"]
for w in test_words:
    print(f"{w}: {word_counts_lit[w]}")

"""build the gender direction"""

import numpy as np
from sklearn.decomposition import PCA

defining_pairs_lit = [
    ("নারী", "পুরুষ"), ("কন্যা", "পুত্র"), ("মা", "বাবা"),
    ("মেয়ে", "ছেলে"), ("রানী", "রাজা"), ("স্ত্রী", "স্বামী"),
    ("ম্যাডাম", "স্যার"),
]

diffs_lit = []
for f_word, m_word in defining_pairs_lit:
    if f_word in model.wv and m_word in model.wv:
        diffs_lit.append(model.wv[f_word] - model.wv[m_word])
        print(f"{f_word} - {m_word}: OK")
    else:
        print(f"{f_word} - {m_word}: MISSING")

diffs_lit = np.array(diffs_lit)
pca_lit = PCA(n_components=min(len(diffs_lit), 10))
pca_lit.fit(diffs_lit)
gender_direction_lit = pca_lit.components_[0]
gap_lit = pca_lit.explained_variance_ratio_[0] - pca_lit.explained_variance_ratio_[1]

np.save(f"{DRIVE_DIR}/gender_direction_literature.npy", gender_direction_lit)
print(f"\nLiterature gender direction computed. PCA gap: {gap_lit:.3f}")



with open("bengali_literature_corpus_v2.txt", encoding="utf-8") as f:
    for i, line in enumerate(f):
        if i in [100, 5000, 50000, 200000, 500000]:
            print(f"Line {i}: {line[:200]}\n")

def clean_wikisource_text_v2(raw_text):
    text = clean_wikisource_text(raw_text)  # your existing cleaning
    text = re.sub(r'\{\{[^}]*\}\}', '', text)  # catch any remaining {{...}} blocks
    text = re.sub(r'col\d*-width=\S+', '', text)  # table column-width leftovers
    text = re.sub(r'\|[^\s]*=\S+', '', text)  # generic key=value table markup
    return text.strip()

# Test example
test_text = "কিছু লেখা {{table|col3-width=5em}} আরো লেখা"
print(clean_wikisource_text_v2(test_text))

import numpy as np

def cosine_sim(vec1, vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

def direct_bias(word, gender_direction, model, c=1):
    if word not in model.wv:
        return None
    vec = model.wv[word]
    cos_sim = cosine_sim(vec, gender_direction)
    return abs(cos_sim) ** c * np.sign(cos_sim)

single words

single_words_lit = {
    "scientist": "বিজ্ঞানী", "musician": "সঙ্গীতশিল্পী", "artist": "শিল্পী",
    "inventor": "উদ্ভাবক", "soldier": "সৈনিক", "journalist": "সাংবাদিক",
    "athlete": "ক্রীড়াবিদ", "ambassador": "রাষ্ট্রদূত", "analyst": "বিশ্লেষক",
    "lawyer": "আইনজীবী", "banker": "ব্যাংকার", "biologist": "জীববিজ্ঞানী",
}

print("=== Bengali Literature: Single-form profession words ===")
results_single_lit = {}
for label, word in single_words_lit.items():
    bias = direct_bias(word, gender_direction_lit, model)
    if bias is not None:
        results_single_lit[label] = float(bias)
        direction = "Female-leaning" if bias > 0 else "Male-leaning"
        print(f"{label:15s} {word:15s} bias: {bias:+.4f}  ({direction})")
    else:
        print(f"{label:15s} {word:15s} NOT FOUND in vocabulary")

"""borrowed/native pairs"""

borrowed_native_pairs_lit = {
    "engineer": [("ইঞ্জিনিয়ার", 0), ("প্রকৌশলী", 0)],
    "manager": [("ম্যানেজার", 0), ("ব্যবস্থাপক", 0)],
    "driver": [("ড্রাইভার", 0), ("চালক", 0)],
    "chef": [("শেফ", 0), ("রাঁধুনি", 0)],
    "governor": [("গভর্নর", 0), ("রাজ্যপাল", 0)],
    "worker": [("শ্রমিক", 0), ("কর্মী", 0)],
    "person": [("ব্যক্তি", 0), ("মানুষ", 0)],
}

for label, forms in borrowed_native_pairs_lit.items():
    borrowed_native_pairs_lit[label] = [(w, word_counts_lit[w]) for w, _ in forms]

print("=== Bengali Literature: Borrowed/Native pairs ===")
results_dual_lit = {}
for label, forms in borrowed_native_pairs_lit.items():
    total_count = sum(count for _, count in forms)
    if total_count == 0:
        print(f"{label:12s} SKIPPED — zero total count")
        continue
    weighted_bias = 0
    detail = []
    for word, count in forms:
        bias = direct_bias(word, gender_direction_lit, model)
        if bias is not None:
            weighted_bias += bias * (count / total_count)
            detail.append(f"{word}({count})={bias:+.4f}")
    results_dual_lit[label] = float(weighted_bias)
    print(f"{label:12s} weighted bias: {weighted_bias:+.4f}   [{', '.join(detail)}]")

"""gendered pairs"""

gendered_pairs_lit = {
    "teacher": [("শিক্ষক", word_counts_lit["শিক্ষক"]), ("শিক্ষিকা", word_counts_lit["শিক্ষিকা"])],
    "actor": [("অভিনেতা", word_counts_lit["অভিনেতা"]), ("অভিনেত্রী", word_counts_lit["অভিনেত্রী"])],
    "writer": [("লেখক", word_counts_lit["লেখক"]), ("লেখিকা", word_counts_lit["লেখিকা"])],
    "nurse": [("নার্স", word_counts_lit["নার্স"]), ("সেবিকা", word_counts_lit["সেবিকা"])],
    "student": [("ছাত্র", word_counts_lit["ছাত্র"]), ("ছাত্রী", word_counts_lit["ছাত্রী"]), ("শিক্ষার্থী", word_counts_lit["শিক্ষার্থী"])],
}

print("=== Bengali Literature: Gendered pairs ===")
results_gendered_lit = {}
for label, forms in gendered_pairs_lit.items():
    total_count = sum(count for _, count in forms)
    if total_count == 0:
        print(f"{label:12s} SKIPPED — zero total count")
        continue
    weighted_bias = 0
    detail = []
    for word, count in forms:
        bias = direct_bias(word, gender_direction_lit, model)
        if bias is not None:
            weighted_bias += bias * (count / total_count)
            detail.append(f"{word}({count})={bias:+.4f}")
    results_gendered_lit[label] = float(weighted_bias)
    print(f"{label:12s} weighted bias: {weighted_bias:+.4f}   [{', '.join(detail)}]")

"""multi-word phrases"""

full_text_lit = open("bengali_literature_corpus_v2.txt", encoding="utf-8").read()

def multiword_vector(phrase_words, model):
    vecs = [model.wv[w] for w in phrase_words if w in model.wv]
    if not vecs:
        return None
    return np.mean(vecs, axis=0)

def direct_bias_vec(vec, gender_direction, c=1):
    cos_sim = cosine_sim(vec, gender_direction)
    return abs(cos_sim) ** c * np.sign(cos_sim)

filmmaker_vec_lit = multiword_vector(["চলচ্চিত্র", "নির্মাতা"], model)
if filmmaker_vec_lit is not None:
    bias_filmmaker_lit = float(direct_bias_vec(filmmaker_vec_lit, gender_direction_lit))
    print(f"filmmaker: {bias_filmmaker_lit:+.4f}")

comedian_m_vec_lit = multiword_vector(["কৌতুক", "অভিনেতা"], model)
comedian_f_vec_lit = multiword_vector(["কৌতুক", "অভিনেত্রী"], model)
if comedian_m_vec_lit is not None and comedian_f_vec_lit is not None:
    bias_m_lit = float(direct_bias_vec(comedian_m_vec_lit, gender_direction_lit))
    bias_f_lit = float(direct_bias_vec(comedian_f_vec_lit, gender_direction_lit))
    count_m_lit = full_text_lit.count("কৌতুক অভিনেতা")
    count_f_lit = full_text_lit.count("কৌতুক অভিনেত্রী")
    total_lit = count_m_lit + count_f_lit
    if total_lit > 0:
        weighted_comedian_lit = (bias_m_lit * count_m_lit + bias_f_lit * count_f_lit) / total_lit
        print(f"comedian: {weighted_comedian_lit:+.4f}")

count_m_lit = full_text_lit.count("কৌতুক অভিনেতা")
count_f_lit = full_text_lit.count("কৌতুক অভিনেত্রী")
print(f"comedian(M) count: {count_m_lit}")
print(f"comedian(F) count: {count_f_lit}")

all_results_lit = {}
all_results_lit.update(results_single_lit)
all_results_lit.update(results_dual_lit)
all_results_lit.update(results_gendered_lit)
all_results_lit["filmmaker"] = -0.1530

print(f"Total professions with data: {len(all_results_lit)} out of 32")
print("\n=== Bengali Literature: All Available Bias Scores ===")
for label, bias in sorted(all_results_lit.items(), key=lambda x: x[1]):
    direction = "Female" if bias > 0 else "Male"
    print(f"{label:15s} {bias:+.4f}  ({direction})")

all_profession_labels = ["scientist","musician","artist","inventor","soldier","journalist","athlete",
               "ambassador","analyst","lawyer","banker","biologist","engineer","manager",
               "driver","chef","governor","worker","person","teacher","actor","writer",
               "nurse","student","filmmaker","comedian","adventurer","aide","astronaut",
               "astronomer","judge"]

missing = set(all_profession_labels) - set(all_results_lit.keys())
print(f"\nMissing from corpus entirely ({len(missing)} professions): {missing}")

# Corpus-level simple average (only for professions that could be measured)
simple_avg_lit = sum(all_results_lit.values()) / len(all_results_lit)
print(f"\nSimple average (measurable professions only): {simple_avg_lit:+.4f}")

import json
with open(f"{DRIVE_DIR}/bias_scores_literature.json", "w", encoding="utf-8") as f:
    json.dump(all_results_lit, f, ensure_ascii=False, indent=2)
print("Saved to Drive.")

"""Mount Drive (if not already done)"""

from google.colab import drive
drive.mount('/content/drive')

"""Copy the file back from Drive to your local working directory"""

!cp "/content/drive/MyDrive/Bengali_Literature_NLP_Bias_Project/bengali_literature_corpus_v2.txt" .

"""Verify it copied successfully"""

!ls -lh bengali_literature_corpus_v2.txt

"""Now run your original sampling code"""

import random

with open("bengali_literature_corpus_v2.txt", encoding="utf-8") as f:
    lines = f.readlines()

print(f"Total lines: {len(lines)}")

random.seed(42)
sample_indices = random.sample(range(len(lines)), 20)
for i in sample_indices:
    print(f"\n--- Line {i} ---")
    print(lines[i][:300])

"""Extract the actual book titles from your raw dump"""

!cp "/content/drive/MyDrive/Bengali_Literature_NLP_Bias_Project/bnwikisource-latest-pages-meta-current.xml.bz2" . 2>/dev/null || echo "Need to re-download if not on Drive"

!wget https://dumps.wikimedia.org/bnwikisource/latest/bnwikisource-latest-pages-meta-current.xml.bz2

"""verify it downloaded correctly"""

!ls -lh bnwikisource-latest-pages-meta-current.xml.bz2

"""proceed with the title extraction"""

import re
import bz2
from collections import Counter

title_counts = Counter()
with bz2.open("bnwikisource-latest-pages-meta-current.xml.bz2", "rt", encoding="utf-8") as f:
    for line in f:
        match = re.search(r'<pages index="([^"]+)"', line)
        if match:
            title_counts[match.group(1)] += 1

print(f"Total unique source titles: {len(title_counts)}")
print("\n=== Most frequently referenced titles (likely largest works) ===")
for title, count in title_counts.most_common(30):
    print(f"{count:5d}  {title}")

!ls -lh bnwikisource-latest-pages-meta-current.xml.bz2

!ls -lh bnwikisource-latest-pages-meta-current.xml.bz2

import bz2

with bz2.open("bnwikisource-latest-pages-meta-current.xml.bz2", "rt", encoding="utf-8") as f:
    for i, line in enumerate(f):
        if "pages index" in line or "<pages" in line:
            print(line)
            break
        if i > 1000000:
            print("Searched 1,000,000 lines, no match found, stopping.")
            break

"""Fixed extraction code"""

import re
import bz2
import html
from collections import Counter

title_counts = Counter()
with bz2.open("bnwikisource-latest-pages-meta-current.xml.bz2", "rt", encoding="utf-8") as f:
    for line in f:
        if "pages index" in line:
            unescaped = html.unescape(line)
            match = re.search(r'<pages index="([^"]+)"', unescaped)
            if match:
                title_counts[match.group(1)] += 1

print(f"Total unique source titles: {len(title_counts)}")
print("\n=== Most frequently referenced titles (likely largest works) ===")
for title, count in title_counts.most_common(30):
    print(f"{count:5d}  {title}")

"""sub meta history"""

!wget https://dumps.wikimedia.org/bnwiki/latest/bnwiki-latest-stub-meta-history.xml.gz

"""extract the file"""

import gzip
import re

creation_dates = []
in_page = False
in_ns0 = False
found_first_timestamp = False

with gzip.open("bnwiki-latest-stub-meta-history.xml.gz", "rt", encoding="utf-8") as f:
    for line in f:
        if "<page>" in line:
            in_page = True
            in_ns0 = False
            found_first_timestamp = False
        if in_page and "<ns>0</ns>" in line:
            in_ns0 = True
        if in_page and in_ns0 and not found_first_timestamp:
            match = re.search(r'<timestamp>([\d-]+)T', line)
            if match:
                creation_dates.append(match.group(1))
                found_first_timestamp = True
        if "</page>" in line:
            in_page = False

print(f"Total articles with a creation date: {len(creation_dates)}")

import matplotlib.pyplot as plt
from collections import Counter

year_months = [d[:7] for d in creation_dates]
counts = Counter(year_months)
sorted_months = sorted(counts.keys())
values = [counts[m] for m in sorted_months]

plt.figure(figsize=(16, 6))
plt.plot(sorted_months, values, linewidth=1)
plt.xticks(sorted_months[::12], rotation=45, fontsize=8)
plt.xlabel("Year-Month")
plt.ylabel("Number of NEW articles created that month")
plt.title("Bengali Wikipedia: True Article Creation Dates Over Time")
plt.tight_layout()
plt.savefig("bengali_wikipedia_creation_timeline.png", dpi=150)
plt.show()

from google.colab import files
files.download("bengali_wikipedia_creation_timeline.png")

"""mount"""

from google.colab import drive
drive.mount('/content/drive')
!cp "/content/drive/MyDrive/Bengali_Literature_NLP_Bias_Project/bengali_literature_corpus_v2.txt" .

"""first simply import some random lines again"""

import random
with open ("bengali_literature_corpus_v2.txt", encoding="utf-8") as f:
    lines = f.readlines()

random.seed(7)
sample_indices = random.sample(range(len(lines)), 20)
for i in sample_indices:
    print(f"\n--- Line {i} ---")
    print(lines[i][:400])

import random
with open ("bengali_literature_corpus_v2.txt", encoding="utf-8") as f:
    lines = f.readlines()

random.seed(6)
sample_indices = random.sample(range(len(lines)), 20)
for i in sample_indices:
    print(f"\n--- Line {i} ---")
    print(lines[i][:400])