# -*- coding: utf-8 -*-
"""Copy of Adding_Bangla_Language.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x4h0MWth_n-UfYLvGZOG1OtIBHrDJ00y
"""

!wget https://dumps.wikimedia.org/bnwiki/latest/bnwiki-latest-pages-articles.xml.bz2

!pip install wikiextractor

!python -m wikiextractor.WikiExtractor bnwiki-latest-pages-articles.xml.bz2 --output extracted_bn --json --processes 4

!sed -n '375,385p' /usr/local/lib/python3.12/dist-packages/wikiextractor/extract.py

!sed -i "s/'\\\\\[(((?i)' + '|'.join(wgUrlProtocols) + ')'/'(?i)\\\\[((' + '|'.join(wgUrlProtocols) + ')'/" /usr/local/lib/python3.12/dist-packages/wikiextractor/extract.py

!sed -n '378,381p' /usr/local/lib/python3.12/dist-packages/wikiextractor/extract.py

path = "/usr/local/lib/python3.12/dist-packages/wikiextractor/extract.py"

with open(path, "r", encoding="utf-8") as f:
    content = f.read()

old2 = "\\.((?i)gif|png|jpg|jpeg)$"
new2 = "\\.((?i:gif|png|jpg|jpeg))$"

if old2 in content:
    content = content.replace(old2, new2)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print("Fix 2 applied successfully.")
else:
    print("Fix 2 pattern not found — check exact text below.")

!sed -n '381,384p' /usr/local/lib/python3.12/dist-packages/wikiextractor/extract.py

!python -c "from wikiextractor.extract import Extractor; print('Import OK')"

!python -m wikiextractor.WikiExtractor bnwiki-latest-pages-articles.xml.bz2 --output extracted_bn --json --processes 4

!find extracted_bn -type f | head -20
!find extracted_bn -type f | wc -l

"""Now let's combine them into one clean text file:"""

import json
import os

output_file = "bengali_corpus.txt"
count = 0

with open(output_file, "w", encoding="utf-8") as f_out:
    for root, dirs, files in os.walk("extracted_bn"):
        for filename in files:
            filepath = os.path.join(root, filename)
            with open(filepath, "r", encoding="utf-8") as f_in:
                for line in f_in:
                    try:
                        article = json.loads(line)
                        text = article.get("text", "").strip()
                        if text:
                            f_out.write(text + "\n")
                            count += 1
                    except json.JSONDecodeError:
                        continue

print(f"Done. Wrote {count} articles to {output_file}")

!ls -lh bengali_corpus.txt
!head -c 500 bengali_corpus.txt

"""Step 1: Mount your Google Drive in Colab"""

from google.colab import drive
drive.mount('/content/drive')

"""Step 2: Create a folder in your Drive and copy your corpus there
This copies your cleaned corpus (1.2GB) into a permanent folder in your Drive called Bengali_NLP_Bias_Project.
"""

import os
os.makedirs('/content/drive/MyDrive/Bengali_NLP_Bias_Project', exist_ok=True)

!cp bengali_corpus.txt /content/drive/MyDrive/Bengali_NLP_Bias_Project/

"""Step 3: Going forward, save your Word2Vec model directly to Drive too, instead of just the local Colab storage:
Why this matters practically: If your Colab session disconnects mid-training (which does happen, especially on the free tier), you'd otherwise have to redo the entire download → extract → clean pipeline from scratch. Saving to Drive means you can always reload bengali_corpus.txt from Drive in a fresh Colab session and pick up right where you left off, without re-running WikiExtractor.
"""

model.save("/content/drive/MyDrive/Bengali_NLP_Bias_Project/bengali_word2vec.model")

"""Step 2: Create the project folder and copy your corpus there (if you haven't already)"""

import os
os.makedirs('/content/drive/MyDrive/Bengali_NLP_Bias_Project', exist_ok=True)
!cp bengali_corpus.txt /content/drive/MyDrive/Bengali_NLP_Bias_Project/

"""Step 3: Now actually train the Word2Vec model (this is the step that creates the model variable):"""

!pip install gensim

from gensim.models import Word2Vec
import re

def tokenize(text):
    text = re.sub(r'[।,.!?"()\[\]—-]', ' ', text)
    return text.split()

print("Reading and tokenizing corpus...")
sentences = []
with open("bengali_corpus.txt", encoding="utf-8") as f:
    for i, line in enumerate(f):
        tokens = tokenize(line)
        if tokens:
            sentences.append(tokens)
        if i % 20000 == 0:
            print(f"Processed {i} lines...")

print(f"Total sentences: {len(sentences)}")

print("Training Word2Vec model...")
model = Word2Vec(
    sentences,
    vector_size=300,
    window=5,
    min_count=5,
    workers=4,
    sg=1
)

print("Training complete.")

"""Step 1: Save the model to Google Drive"""

model.save("/content/drive/MyDrive/Bengali_NLP_Bias_Project/bengali_word2vec.model")
print("Model saved to Drive.")

"""Step 2: Sanity check — see what words are most similar to "বাংলা" (Bengali)

Not quite — this line doesn't count how many times "বাংলা" appears (that's what your earlier word_counts["বাংলা"] code did). This is checking something different: which other words in the model are mathematically most similar to "বাংলা," based on the vector it learned during training.
"""

print(model.wv.most_similar("বাংলা", topn=5))

"""Now let's run Step 2 — checking your actual defining-set/profession-set words:"""

test_words = ["নারী", "পুরুষ", "নার্স", "সেবিকা", "প্রকৌশলী", "ইঞ্জিনিয়ার", "শিক্ষক", "শিক্ষিকা"]

for word in test_words:
    if word in model.wv:
        print(f"{word}: found in vocabulary")
    else:
        print(f"{word}: NOT FOUND — check spelling or min_count threshold")

"""Counting word frequencies across corpus (this may take a few minutes)...
Done counting.


**This code counts words directly from the raw text file (bengali_corpus.txt) — completely separately from the trained model.**

Step by step:

o**pen("bengali_corpus.txt", ...)** — this reopens your original 1.2GB plain text corpus file (the same one you used earlier to train Word2Vec)
**for line in f:** — it reads through that file line by line, from scratch, independently of any training that already happened
**tokenize(line)** — splits each line into individual words (stripping punctuation)
**word_counts.update(tokens)** — tallies up how many times each word appears, across the entire raw text

Key distinction — this counts EVERY word in the raw text, including words that Word2Vec later excluded:
Remember, when you trained Word2Vec with min_count=5, any word appearing fewer than 5 times got dropped from model.wv — those words simply don't exist in the trained vocabulary. But this counting code doesn't know or care about that min_count threshold at all — it counts absolutely every word in the raw text, even ones appearing only once, since it's working directly with the original text file, not with model.wv.
"""

from collections import Counter
import re

def tokenize(text):
    text = re.sub(r'[।,.!?"()\[\]—\-\'‘’]', ' ', text)
    return text.split()

print("Counting word frequencies across corpus (this may take a few minutes)...")
word_counts = Counter()
with open("bengali_corpus.txt", encoding="utf-8") as f:
    for line in f:
        word_counts.update(tokenize(line))

print("Done counting.")

"""Save word_counts to Drive"""

import pickle

with open("/content/drive/MyDrive/Bengali_NLP_Bias_Project/word_counts.pkl", "wb") as f:
    pickle.dump(word_counts, f)

print("word_counts saved to Drive.")

"""Now, since word_counts is already in memory in this session, go ahead and run the second block right now to see your actual results:


***It's counting how many times these words appear in the raw text file (bengali_corpus.txt)***
"""

defining_set = {
    "নারী": "woman", "পুরুষ": "man",
    "কন্যা": "daughter", "পুত্র": "son",
    "মা": "mother", "বাবা": "father",
    "মেয়ে": "girl", "ছেলে": "boy",
    "রানী": "queen", "রাজা": "king",
    "স্ত্রী": "wife", "স্বামী": "husband",
    "ম্যাডাম": "madam", "স্যার": "sir",
}

profession_set = {
    "নার্স": "nurse(E)", "সেবিকা": "nurse(native,F)",
    "শিক্ষক": "teacher(M)", "শিক্ষিকা": "teacher(F)",
    "লেখক": "writer", "লেখিকা": "writer(F)",
    "ইঞ্জিনিয়ার": "engineer(E)", "প্রকৌশলী": "engineer(native)",
    "বিজ্ঞানী": "scientist",
    "ম্যানেজার": "manager(E)", "ব্যবস্থাপক": "manager(native)",
    "ড্রাইভার": "driver(E)", "চালক": "driver(native)",
    "ব্যাংকার": "banker",
    "সঙ্গীতশিল্পী": "musician",
    "শিল্পী": "artist",
    "শেফ": "chef(E)", "রাঁধুনি": "chef(native)",
    "বিচারক": "judge",
    "উদ্ভাবক": "inventor",
    "শ্রমিক": "worker(1)", "কর্মী": "worker(2)",
    "সৈনিক": "soldier",
    "সাংবাদিক": "journalist",
    "শিক্ষার্থী": "student(N)", "ছাত্র": "student(M)", "ছাত্রী": "student(F)",
    "ক্রীড়াবিদ": "athlete",
    "অভিনেতা": "actor(M)", "অভিনেত্রী": "actor(F)",
    "গভর্নর": "governor(E)", "রাজ্যপাল": "governor(native)",
    "কৃষক": "farmer",
    "ব্যক্তি": "person(1)", "মানুষ": "person(2)",
    "আইনজীবী": "lawyer",
    "অভিযাত্রী": "adventurer",
    "সহকারী": "aide",
    "রাষ্ট্রদূত": "ambassador",
    "বিশ্লেষক": "analyst",
    "নভোচারী": "astronaut",
    "জ্যোতির্বিজ্ঞানী": "astronomer",
    "জীববিজ্ঞানী": "biologist",
}

print("=== Defining Set Word Counts ===")
for word, label in defining_set.items():
    print(f"{label:20s} {word:15s} N: {word_counts[word]:,}")

print("\n=== Profession Set Word Counts ===")
for word, label in profession_set.items():
    print(f"{label:20s} {word:15s} N: {word_counts[word]:,}")

print("\n=== Multi-word Phrases (substring count in raw text) ===")
full_text = open("bengali_corpus.txt", encoding="utf-8").read()
multi_word = {
    "চলচ্চিত্র নির্মাতা": "filmmaker",
    "কৌতুক অভিনেতা": "comedian(M)",
    "কৌতুক অভিনেত্রী": "comedian(F)",
}
for phrase, label in multi_word.items():
    print(f"{label:20s} {phrase:25s} count: {full_text.count(phrase):,}")

"""First, let's save this data so it's not lost:"""

import json

results = {
    "defining_set": {label: word_counts[word] for word, label in defining_set.items()},
    "profession_set": {label: word_counts[word] for word, label in profession_set.items()},
}

with open("/content/drive/MyDrive/Bengali_NLP_Bias_Project/word_count_results.json", "w", encoding="utf-8") as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

print("Word count results saved to Drive.")

"""**Now let's move to the actual bias calculation — this is the core of the whole methodology.**

*Step 1: Build the Gender Direction from our 7 defining pairs*

This code takes our 7 defining word pairs (woman-man, daughter-son, etc.) and calculates the vector difference for each pair — essentially "female word minus male word". For each pair, it checks that both words actually exist in our trained Word2Vec model, calculates the difference (female vector − male vector), and collects all these differences into a list. At the end, it tells you how many of the 7 pairs were successfully processed (ideally all 7, but it'll flag and skip any pair where one of the words wasn't found in the vocabulary). These 7 (or however many succeed) difference vectors are the raw ingredients that the next step (PCA) will use to calculate the overall "gender direction" — the mathematical compass that every profession word will later be compared against.

***this step is purely about calculating those 7 individual differences***
"""

import numpy as np

defining_pairs = [
    ("নারী", "পুরুষ"),      # woman - man
    ("কন্যা", "পুত্র"),      # daughter - son
    ("মা", "বাবা"),          # mother - father
    ("মেয়ে", "ছেলে"),       # girl - boy
    ("রানী", "রাজা"),        # queen - king
    ("স্ত্রী", "স্বামী"),     # wife - husband
    ("ম্যাডাম", "স্যার"),    # madam - sir
]

diffs = []
for female_word, male_word in defining_pairs:
    if female_word in model.wv and male_word in model.wv:
        diff = model.wv[female_word] - model.wv[male_word]
        diffs.append(diff)
        print(f"{female_word} - {male_word}: OK")
    else:
        print(f"{female_word} - {male_word}: MISSING from vocabulary — skipped")

diffs = np.array(diffs)
print(f"\nCollected {len(diffs)} valid pair differences out of {len(defining_pairs)}")

"""save this results"""

import numpy as np

np.save("/content/drive/MyDrive/Bengali_NLP_Bias_Project/defining_set_diffs.npy", diffs)
print("Defining set differences saved to Drive.")

"""Now let's move to Step 2 — **run PCA to get the actual gender direction:**
This code runs PCA (the dimension-reduction technique we discussed earlier) on your 7 defining-set difference vectors. It looks at all 7 differences together and finds the "1st pattern" — the single strongest, most common direction they mostly agree on — which becomes your gender direction, the compass every profession word will later be measured against. It also prints the "explained variance ratio" for the top few patterns, showing how much of the overall variation each pattern captures, and calculates the gap between the 1st and 2nd pattern. A large gap means the 7 pairs strongly agree on one clear "gender" direction (trustworthy, like most languages in the original paper); a small gap (like Chinese's 0.06) would mean the pairs don't agree well enough to confidently call it "pure gender" — signaling a potential issue with Bengali's defining set, the same problem the original paper found with Chinese.

**Here we import PCA and do some calculation**
"""

from sklearn.decomposition import PCA

pca = PCA(n_components=min(len(diffs), 10))
pca.fit(diffs)

gender_direction = pca.components_[0]  # first principal component

print("Explained variance ratio (top components):")
print(pca.explained_variance_ratio_[:5])
print(f"\nGap between 1st and 2nd component: {pca.explained_variance_ratio_[0] - pca.explained_variance_ratio_[1]:.3f}")

"""Where Bengali lands: Your gap of 0.134 sits between German (0.17) and Arabic (0.11) — closer to the lower end of the scale, but nowhere near as problematic as Chinese's 0.06. This means Bengali's defining set captures a reasonably identifiable gender direction, though not as cleanly as languages like Spanish, French, or English.

What this means practically: Your 1st PCA component does appear to meaningfully represent gender more than the 2nd component, so it's reasonable to proceed with using it as your gender direction — but this is a good moment to flag (in your paper's limitations/discussion section) that Bengali's separation isn't as strong as the top-performing languages, similar to how the original paper flagged Arabic's German's more moderate scores.

Possible reason worth investigating (optional, for later): Since Bengali doesn't strongly mark grammatical gender the way German/Arabic do, the "extra" variation captured by non-gender components might be coming from something like formality register or semantic category differences between your word pairs (e.g., queen-king carrying "royalty" connotations, madam-sir carrying "formality" connotations) — similar to what the original paper speculated about their own results.

Let's save this and move to the actual DirectBias calculations for your 32 profession words:
"""

np.save("/content/drive/MyDrive/Bengali_NLP_Bias_Project/gender_direction.npy", gender_direction)
print("Gender direction saved to Drive.")

"""Here we calculated the actual DirectBias scores for all our profession words, following Formula 1 from the paper.

Step 3: DirectBias calculation

this entire step is specifically about figuring out, for each of our 32 profession words, whether the word's real-world usage pattern in Bengali Wikipedia leans toward representing "male" or "female" concepts — and by how much. That's the whole point of the DirectBias calculation, and it's the final, actual output our whole project has been building toward.
"""

import numpy as np

def cosine_sim(vec1, vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

def direct_bias(word, gender_direction, model, c=1):
    if word not in model.wv:
        return None
    vec = model.wv[word]
    cos_sim = cosine_sim(vec, gender_direction)
    return abs(cos_sim) ** c * np.sign(cos_sim)  # keep sign to show direction (F/M)

# Single-form (clean/neutral) profession words
single_words = {
    "scientist": "বিজ্ঞানী",
    "musician": "সঙ্গীতশিল্পী",
    "artist": "শিল্পী",
    "judge": "বিচারক",
    "inventor": "উদ্ভাবক",
    "soldier": "সৈনিক",
    "journalist": "সাংবাদিক",
    "athlete": "ক্রীড়াবিদ",
    "farmer": "কৃষক",
    "lawyer": "আইনজীবী",
    "adventurer": "অভিযাত্রী",
    "aide": "সহকারী",
    "ambassador": "রাষ্ট্রদূত",
    "analyst": "বিশ্লেষক",
    "astronaut": "নভোচারী",
    "astronomer": "জ্যোতির্বিজ্ঞানী",
    "biologist": "জীববিজ্ঞানী",
    "banker": "ব্যাংকার",
}

print("=== Single-form profession words ===")
results_single = {}
for label, word in single_words.items():
    bias = direct_bias(word, gender_direction, model)
    results_single[label] = bias
    direction = "Female-leaning" if bias > 0 else "Male-leaning"
    print(f"{label:15s} {word:15s} bias: {bias:+.4f}  ({direction})")

"""Good — real bias scores for 18 professions. Let's flag a few notable patterns before moving on:

Strongest male-leaning: analyst (-0.134), adventurer (-0.130), scientist (-0.127), biologist (-0.103)
Strongest female-leaning: musician (0.095), artist (0.078)
Nearly neutral (close to zero, worth noting as "no strong bias"): aide (0.004), astronaut (0.002), ambassador (-0.004), judge (-0.009)

Interesting parallel to the original paper: "scientist" leaning male here roughly echoes patterns seen in other languages (like German's scientist example), while "musician" and "artist" leaning female is a distinctly Bengali-specific pattern worth discussing.

Now let's handle the remaining words — first the borrowed/native pairs that are both neutral (need combining), then the genuinely gendered pairs (need weighted average by frequency).

Step 3b: Borrowed/native pairs (combine using frequency-weighted average, treating both as one "concept")
"""

borrowed_native_pairs = {
    "engineer": [("ইঞ্জিনিয়ার", 1093), ("প্রকৌশলী", 2494)],
    "manager": [("ম্যানেজার", 2184), ("ব্যবস্থাপক", 992)],
    "driver": [("ড্রাইভার", 477), ("চালক", 983)],
    "chef": [("শেফ", 275), ("রাঁধুনি", 144)],
    "governor": [("গভর্নর", 8169), ("রাজ্যপাল", 740)],
    "worker": [("শ্রমিক", 4760), ("কর্মী", 7015)],
    "person": [("ব্যক্তি", 17771), ("মানুষ", 19849)],
}

print("=== Borrowed/Native pairs (frequency-weighted average) ===")
results_dual = {}
for label, forms in borrowed_native_pairs.items():
    total_count = sum(count for _, count in forms)
    weighted_bias = 0
    detail = []
    for word, count in forms:
        bias = direct_bias(word, gender_direction, model)
        weighted_bias += bias * (count / total_count)
        detail.append(f"{word}({count})={bias:+.4f}")
    results_dual[label] = weighted_bias
    print(f"{label:12s} weighted bias: {weighted_bias:+.4f}   [{', '.join(detail)}]")

"""Good — 7 more done. Let's run the last block for the gendered pairs.

Opted for direct response over tool usage
Opted for direct response over tool usage

Good results — a few quick observations:

Governor (-0.141) is now the strongest male-leaning profession in your whole list so far — both borrowed and native forms agree closely (-0.140 and -0.148), which is a consistent, trustworthy result.
Chef (+0.080) and person (+0.084) lean notably female — worth noting alongside musician/artist as a cluster of female-leaning results.
Driver (+0.065) leaning female is a bit surprising/counter-stereotypical — worth flagging as an interesting finding, similar to how the original paper flagged "husband" as an unexpected result.
"""

gendered_pairs = {
    "teacher": [("শিক্ষক", 10373), ("শিক্ষিকা", 811)],
    "actor": [("অভিনেতা", 11753), ("অভিনেত্রী", 13247)],
    "writer": [("লেখক", 15725), ("লেখিকা", 1330)],
    "student": [("ছাত্র", 11843), ("ছাত্রী", 1700), ("শিক্ষার্থী", 5677)],
    "nurse": [("নার্স", 724), ("সেবিকা", 224)],
}

print("=== Gendered pairs (frequency-weighted average) ===")
results_gendered = {}
for label, forms in gendered_pairs.items():
    total_count = sum(count for _, count in forms)
    weighted_bias = 0
    detail = []
    for word, count in forms:
        bias = direct_bias(word, gender_direction, model)
        weighted_bias += bias * (count / total_count)
        detail.append(f"{word}({count})={bias:+.4f}")
    results_gendered[label] = weighted_bias
    print(f"{label:12s} weighted bias: {weighted_bias:+.4f}   [{', '.join(detail)}]")

"""Save all results so far"""

import json

all_results = {
    **results_single,
    **results_dual,
    **results_gendered,
}

# Convert numpy float32 values to plain Python floats
all_results = {label: float(bias) for label, bias in all_results.items()}

with open("/content/drive/MyDrive/Bengali_NLP_Bias_Project/bias_scores.json", "w", encoding="utf-8") as f:
    json.dump(all_results, f, ensure_ascii=False, indent=2)

print(f"Saved {len(all_results)} profession bias scores to Drive.")

print("\n=== All Profession Bias Scores (sorted) ===")
for label, bias in sorted(all_results.items(), key=lambda x: x[1]):
    direction = "Female" if bias > 0 else "Male"
    print(f"{label:15s} {bias:+.4f}  ({direction})")

"""Run the filmmaker/comedian block now:

Filmmaker and comedian in Bengali are two-word phrases (like "film-maker"), so Word2Vec never learned a single vector for the whole phrase — only for each individual word separately. To work around this, we averaged the vectors of the component words together (e.g., চলচ্চিত্র + নির্মাতা) to create an approximate combined vector for the whole phrase, then ran the same bias calculation on that averaged vector as we did for every other word. For comedian specifically, since it also has separate male and female forms, we did this component-averaging twice (once for the male phrase, once for the female phrase), then combined those two results using the same frequency-weighted averaging method used earlier for teacher/actor/writer — giving one final bias score for comedian overall.
"""

def multiword_vector(phrase_words, model):
    vecs = [model.wv[w] for w in phrase_words if w in model.wv]
    if not vecs:
        return None
    return np.mean(vecs, axis=0)

def direct_bias_vec(vec, gender_direction, c=1):
    cos_sim = cosine_sim(vec, gender_direction)
    return abs(cos_sim) ** c * np.sign(cos_sim)

filmmaker_vec = multiword_vector(["চলচ্চিত্র", "নির্মাতা"], model)
if filmmaker_vec is not None:
    bias = float(direct_bias_vec(filmmaker_vec, gender_direction))
    print(f"filmmaker (component-avg): {bias:+.4f}")
else:
    print("filmmaker: components not found in vocabulary")

comedian_m_vec = multiword_vector(["কৌতুক", "অভিনেতা"], model)
comedian_f_vec = multiword_vector(["কৌতুক", "অভিনেত্রী"], model)

if comedian_m_vec is not None and comedian_f_vec is not None:
    bias_m = float(direct_bias_vec(comedian_m_vec, gender_direction))
    bias_f = float(direct_bias_vec(comedian_f_vec, gender_direction))
    weighted_comedian = (bias_m * 273 + bias_f * 28) / (273 + 28)
    print(f"comedian(M, component-avg): {bias_m:+.4f}")
    print(f"comedian(F, component-avg): {bias_f:+.4f}")
    print(f"comedian(weighted avg): {weighted_comedian:+.4f}")
else:
    print("comedian: components not found in vocabulary")

"""All 32 professions now have bias scores. This is a complete, real dataset — a genuine milestone. Let's compile everything into the final full ranking and calculate the overall corpus-level score.

Compile the complete 32-word ranking
"""

all_results["filmmaker"] = 0.0913
all_results["comedian"] = 0.0946

with open("/content/drive/MyDrive/Bengali_NLP_Bias_Project/bias_scores.json", "w", encoding="utf-8") as f:
    json.dump(all_results, f, ensure_ascii=False, indent=2)

print(f"Total professions with bias scores: {len(all_results)}")

print("\n=== COMPLETE Bengali Profession Bias Ranking (32 words) ===")
for label, bias in sorted(all_results.items(), key=lambda x: x[1]):
    direction = "Female" if bias > 0 else "Male"
    print(f"{label:15s} {bias:+.4f}  ({direction})")

"""Based on your 32 values, the simple average works out to ≈ -0.0022 — essentially dead neutral, just barely tilting male, practically negligible.

This is a genuinely interesting and nuanced result — here's how to read it:

1. The individual professions show a real pattern: 21 lean female, 11 lean male — clearly more professions skew female than male when you just count directions.

2. But the overall average is nearly perfectly balanced (-0.0022). This happens because the male-leaning professions have noticeably larger magnitudes (governor -0.14, analyst -0.13, adventurer -0.13, scientist -0.13) compared to the female-leaning professions, which cluster more tightly around smaller values (mostly +0.01 to +0.09). So even though more professions lean female, the male-leaning ones "pull harder," roughly balancing the average out.

This is actually a really nice, nuanced finding for your paper — quite different from simply saying "Bengali leans male" or "Bengali leans female." The honest, careful conclusion is: Bengali Wikipedia shows a wider spread and greater number of female-leaning professions, but a smaller number of male-leaning professions carry stronger bias magnitudes, resulting in a near-neutral overall average.

Comparing to the original paper's Figure 7 results: Most languages (Arabic, English, Farsi, French, German, Urdu) showed a clearly negative (male) overall corpus average. Bengali's near-zero result is genuinely distinctive — not clearly male-leaning like most of the original 9 languages, and not clearly female-leaning either.

Let's also calculate the frequency-weighted average (matching the original paper's more rigorous approach, weighting each profession by how often it actually appears in the corpus — using your earlier word counts):

**This code calculates one single overall corpus-level bias score for Bengali — combining all 32 professions into one final number, matching Figure 7 from the original paper.**
"""

profession_counts = {
    "scientist": 4131, "musician": 1530, "artist": 7735, "judge": 3520, "inventor": 731,
    "soldier": 2020, "journalist": 5289, "athlete": 1085, "farmer": 3355, "lawyer": 4323,
    "adventurer": 803, "aide": 6328, "ambassador": 2206, "analyst": 657, "astronaut": 214,
    "astronomer": 637, "biologist": 494, "banker": 341,
    "engineer": 1093+2494, "manager": 2184+992, "driver": 477+983, "chef": 275+144,
    "governor": 8169+740, "worker": 4760+7015, "person": 17771+19849,
    "teacher": 10373+811, "actor": 11753+13247, "writer": 15725+1330,
    "student": 11843+1700+5677, "nurse": 724+224,
    "filmmaker": 1503, "comedian": 273+28,
}

total_count = sum(profession_counts[label] for label in all_results.keys())
weighted_avg = sum(all_results[label] * profession_counts[label] for label in all_results.keys()) / total_count

print(f"Frequency-weighted average bias: {weighted_avg:+.4f}")
print(f"Overall (weighted): {'Female-leaning' if weighted_avg > 0 else 'Male-leaning'}")

"""This is a genuinely notable finding — and it directly parallels one of the most interesting results from the original paper.

Summary of your two averages:

Simple average: -0.0022 (essentially neutral, barely male)
Weighted average: +0.0268 (clearly female-leaning)

This mirrors exactly what happened with Spanish in the original paper — remember, Spanish's simple average was male-biased, but its weighted average flipped to female-biased. Bengali shows the same kind of flip, just starting from an even more neutral simple-average baseline.

Why this flip happens: Your frequently-used professions (person: 37,620 combined mentions, actor: 25,000, teacher: 11,184, writer: 17,055) tend to lean female or near-neutral, while some of your strongest male-leaning words (governor: 8,909, analyst: 657, adventurer: 803) are used far less often. Since the weighted average gives more influence to frequently-used words, and those happen to lean female or neutral, the overall weighted result shifts female — even though a plain word-by-word average looked nearly balanced.

How this compares to the original paper's Figure 7 overall:

Language	Overall bias direction
Arabic, English, Farsi, French, German, Urdu	Male-leaning
Spanish (weighted)	Mildly female-leaning
Chinese, Wolof	Unreliable (methodological issues)
Bengali (weighted)	Female-leaning (+0.027)

This makes Bengali the second language in this line of research (after Spanish) to show an overall female-leaning corpus bias — a genuinely interesting, citable finding for your paper's results section.

Let's save this final summary and you'll have your complete results ready to write up:
"""

final_summary = {
    "simple_average": -0.0022,
    "weighted_average": 0.0268,
    "num_professions": 32,
    "num_female_leaning": 21,
    "num_male_leaning": 11,
    "gender_direction_pca_gap": 0.134,
    "corpus_articles": 187772,
    "corpus_size_gb": 1.2,
}

with open("/content/drive/MyDrive/Bengali_NLP_Bias_Project/final_summary.json", "w", encoding="utf-8") as f:
    json.dump(final_summary, f, ensure_ascii=False, indent=2)

print("Final summary saved to Drive.")
print(json.dumps(final_summary, indent=2))

"""Everything's saved. You now have a complete, real, reproducible analysis — this is genuinely solid work. Let's take stock of where you are and figure out the best next move.

What you've accomplished (full pipeline, start to finish):

Translated and validated the 7-pair defining set and 32-word profession set into Bengali, catching real linguistic nuances (gendered forms, borrowed vs. native words, multi-word phrases) along the way
Downloaded, cleaned, and processed the full Bengali Wikipedia (187,772 articles, 1.2GB)
Trained a Word2Vec model from scratch (patching two real Python 3.12 compatibility bugs in WikiExtractor along the way — genuinely useful troubleshooting work)
Calculated the gender direction via PCA (with an honestly-reported reliability gap of 0.134)
Computed DirectBias scores for all 32 professions, using frequency-weighted averages for every word with multiple forms
Found a genuinely interesting result: Bengali shows a simple average near-neutral (-0.0022) but a weighted average that's clearly female-leaning (+0.0268) — mirroring the Spanish "flip" pattern from the original paper


"""