# -*- coding: utf-8 -*-
"""hindi_gender_bias_pipeline.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mkpv64K9oRt033Fsn7ZKrb44wO9UOlH_

Mount Drive and set up a new project folder
"""

from google.colab import drive
drive.mount('/content/drive')

import os
DRIVE_DIR = "/content/drive/MyDrive/Hindi_NLP_Bias_Project"
os.makedirs(DRIVE_DIR, exist_ok=True)

"""Download the Hindi Wikipedia dump"""

!wget https://dumps.wikimedia.org/hiwiki/latest/hiwiki-latest-pages-articles.xml.bz2

"""Install WikiExtractor and apply the same regex patches as before"""

!pip install wikiextractor

path_extract = None
import wikiextractor, os
path_extract = os.path.join(os.path.dirname(wikiextractor.__file__), "extract.py")

with open(path_extract, "r", encoding="utf-8") as f:
    content = f.read()

old1 = "'\\[(((?i)' + '|'.join(wgUrlProtocols) + ')' + EXT_LINK_URL_CLASS"
new1 = "'(?i)\\[((' + '|'.join(wgUrlProtocols) + ')' + EXT_LINK_URL_CLASS"
old2 = "\\.((?i)gif|png|jpg|jpeg)$"
new2 = "\\.((?i:gif|png|jpg|jpeg))$"

if old1 in content:
    content = content.replace(old1, new1)
if old2 in content:
    content = content.replace(old2, new2)

with open(path_extract, "w", encoding="utf-8") as f:
    f.write(content)

print("WikiExtractor patched.")

"""Run extraction"""

!python -m wikiextractor.WikiExtractor hiwiki-latest-pages-articles.xml.bz2 --output extracted_hi --json --processes 4

"""Combine into one clean corpus file, save to Drive"""

import json

count = 0
with open("hindi_corpus.txt", "w", encoding="utf-8") as f_out:
    for root, dirs, files in os.walk("extracted_hi"):
        for filename in files:
            filepath = os.path.join(root, filename)
            with open(filepath, "r", encoding="utf-8") as f_in:
                for line in f_in:
                    try:
                        article = json.loads(line)
                        text = article.get("text", "").strip()
                        if text:
                            f_out.write(text + "\n")
                            count += 1
                    except json.JSONDecodeError:
                        continue

print(f"Wrote {count} articles to hindi_corpus.txt")

!cp hindi_corpus.txt "{DRIVE_DIR}/"

"""Train Word2Vec"""

!pip install gensim
from gensim.models import Word2Vec
import re

def tokenize(text):
    text = re.sub(r'[।,.!?"()\[\]—\-\'‘’]', ' ', text)
    return text.split()

sentences = []
with open("hindi_corpus.txt", encoding="utf-8") as f:
    for line in f:
        tokens = tokenize(line)
        if tokens:
            sentences.append(tokens)

print(f"Total sentences: {len(sentences)}")

model = Word2Vec(sentences, vector_size=300, window=5, min_count=5, workers=4, sg=1)
model.save(f"{DRIVE_DIR}/hindi_word2vec.model")
print("Model trained and saved.")

"""this code takes your cleaned Hindi Wikipedia text, breaks it into individual words per line, and uses that to train a Word2Vec model — learning a 300-number vector representation for every word that appears at least 5 times — then saves the finished model to Drive.

Count word frequencies for your Hindi word list
"""

from collections import Counter
import pickle

word_counts = Counter()
with open("hindi_corpus.txt", encoding="utf-8") as f:
    for line in f:
        word_counts.update(tokenize(line))

with open(f"{DRIVE_DIR}/word_counts.pkl", "wb") as f:
    pickle.dump(word_counts, f)

# Check your key words
test_words = ["महिला", "पुरुष", "नर्स", "परिचारक", "परिचारिका", "शिक्षक", "शिक्षिका"]
for w in test_words:
    print(f"{w}: {word_counts[w]}")

defining_set = {
    "महिला": "woman", "पुरुष": "man",   # Hindi word : English label
    "बेटी": "daughter", "बेटा": "son",
    "माँ": "mother", "पिता": "father",
    "लड़की": "girl", "लड़का": "boy",
    "रानी": "queen", "राजा": "king",
    "पत्नी": "wife", "पति": "husband",
    "मैडम": "madam", "सर": "sir",
}

profession_set = {
    "नर्स": "nurse(E)", "परिचारक": "nurse(M)", "परिचारिका": "nurse(F)",  # Hindi word नर्स → labeled "nurse(E)" = borrowed/English form
    "शिक्षक": "teacher(M)", "शिक्षिका": "teacher(F)",
    "लेखक": "writer(M)", "लेखिका": "writer(F)",
    "इंजीनियर": "engineer(E)", "अभियंता": "engineer(N)",
    "वैज्ञानिक": "scientist",
    "मैनेजर": "manager(E)", "प्रबंधक": "manager(N)",
    "ड्राइवर": "driver(E)", "चालक": "driver(N)",
    "बैंकर": "banker",
    "संगीतकार": "musician",
    "कलाकार": "artist",
    "शेफ": "chef(E)", "रसोइया": "chef(N)",
    "न्यायाधीश": "judge(N)", "जज": "judge(E)",
    "आविष्कारक": "inventor",
    "मज़दूर": "worker(1)", "कर्मचारी": "worker(2)",
    "सैनिक": "soldier",
    "पत्रकार": "journalist",
    "छात्र": "student(M)", "छात्रा": "student(F)", "विद्यार्थी": "student(N)",
    "खिलाड़ी": "athlete",
    "अभिनेता": "actor(M)", "अभिनेत्री": "actor(F)", "ऐक्टर": "actor(E)",
    "गवर्नर": "governor(E)", "राज्यपाल": "governor(N)",
    "किसान": "farmer(1)", "कृषक": "farmer(2)",
    "व्यक्ति": "person(1)", "मनुष्य": "person(2)", "इंसान": "person(3)",
    "वकील": "lawyer",
    "सहायक": "aide(M)", "सहायिका": "aide(F)",
    "राजदूत": "ambassador",
    "विश्लेषक": "analyst",
    "खगोलशास्त्री": "astronomer(1)", "खगोलज्ञ": "astronomer(2)",
    "जीवविज्ञानी": "biologist",
}

print("=== Defining Set Word Counts ===")
for word, label in defining_set.items():
    print(f"{label:15s} {word:10s} N: {word_counts[word]:,}")

print("\n=== Profession Set Word Counts ===")
for word, label in profession_set.items():
    print(f"{label:15s} {word:10s} N: {word_counts[word]:,}")

print("\n=== Multi-word Phrases (substring search) ===")
full_text = open("hindi_corpus.txt", encoding="utf-8").read()
multi_word = {
    "फ़िल्म निर्माता": "filmmaker",
    "हास्य अभिनेता": "comedian(M)",
    "हास्य अभिनेत्री": "comedian(F)",
    "साहसी यात्री": "adventurer",
    "अंतरिक्ष यात्री": "astronaut",
}
for phrase, label in multi_word.items():
    print(f"{label:15s} {phrase:20s} count: {full_text.count(phrase):,}")

import json

results = {
    "defining_set": {label: word_counts[word] for word, label in defining_set.items()},
    "profession_set": {label: word_counts[word] for word, label in profession_set.items()},
}

with open(f"{DRIVE_DIR}/word_count_results.json", "w", encoding="utf-8") as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

print("Saved to Drive.")

"""Build the gender direction"""

import numpy as np
from sklearn.decomposition import PCA

defining_pairs = [
    ("महिला", "पुरुष"), ("बेटी", "बेटा"), ("माँ", "पिता"),
    ("लड़की", "लड़का"), ("रानी", "राजा"), ("पत्नी", "पति"),
    ("मैडम", "सर"),
]

diffs = []
for f_word, m_word in defining_pairs:
    if f_word in model.wv and m_word in model.wv:
        diffs.append(model.wv[f_word] - model.wv[m_word])
        print(f"{f_word} - {m_word}: OK")
    else:
        print(f"{f_word} - {m_word}: MISSING")

diffs = np.array(diffs)
pca = PCA(n_components=min(len(diffs), 10))
pca.fit(diffs)
gender_direction = pca.components_[0]
gap = pca.explained_variance_ratio_[0] - pca.explained_variance_ratio_[1]

np.save(f"{DRIVE_DIR}/gender_direction.npy", gender_direction)
print(f"\nGender direction computed. PCA gap: {gap:.3f}")

"""Core bias function"""

def cosine_sim(vec1, vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

def direct_bias(word, gender_direction, model, c=1):
    if word not in model.wv:
        return None
    vec = model.wv[word]
    cos_sim = cosine_sim(vec, gender_direction)
    return abs(cos_sim) ** c * np.sign(cos_sim)

"""Single-form (clean/neutral) profession words"""

single_words = {
    "scientist": "वैज्ञानिक",
    "musician": "संगीतकार",
    "artist": "कलाकार",
    "inventor": "आविष्कारक",
    "soldier": "सैनिक",
    "journalist": "पत्रकार",
    "athlete": "खिलाड़ी",
    "ambassador": "राजदूत",
    "analyst": "विश्लेषक",
    "lawyer": "वकील",
    "banker": "बैंकर",
    "biologist": "जीवविज्ञानी",
}

print("=== Single-form profession words ===")
results_single = {}
for label, word in single_words.items():
    bias = direct_bias(word, gender_direction, model)
    if bias is not None:
        results_single[label] = float(bias)
        direction = "Female-leaning" if bias > 0 else "Male-leaning"
        print(f"{label:15s} {word:15s} bias: {bias:+.4f}  ({direction})")
    else:
        print(f"{label:15s} {word:15s} NOT FOUND in vocabulary")

"""Borrowed/native pairs (weighted average)"""

borrowed_native_pairs = {
    "engineer": [("इंजीनियर", 0), ("अभियंता", 0)],
    "manager": [("मैनेजर", 0), ("प्रबंधक", 0)],
    "driver": [("ड्राइवर", 0), ("चालक", 0)],
    "chef": [("शेफ", 0), ("रसोइया", 0)],
    "judge": [("जज", 0), ("न्यायाधीश", 0)],
    "governor": [("गवर्नर", 0), ("राज्यपाल", 0)],
    "worker": [("मज़दूर", 0), ("कर्मचारी", 0)],
    "farmer": [("किसान", 0), ("कृषक", 0)],
    "person": [("व्यक्ति", 0), ("मनुष्य", 0), ("इंसान", 0)],
    "astronomer": [("खगोलशास्त्री", 0), ("खगोलज्ञ", 0)],
}

# Fill in real counts from word_counts
for label, forms in borrowed_native_pairs.items():
    borrowed_native_pairs[label] = [(w, word_counts[w]) for w, _ in forms]

print("\n=== Borrowed/Native/Synonym pairs (frequency-weighted average) ===")
results_dual = {}
for label, forms in borrowed_native_pairs.items():
    total_count = sum(count for _, count in forms)
    if total_count == 0:
        print(f"{label:12s} SKIPPED — zero total count")
        continue
    weighted_bias = 0
    detail = []
    for word, count in forms:
        bias = direct_bias(word, gender_direction, model)
        if bias is not None:
            weighted_bias += bias * (count / total_count)
            detail.append(f"{word}({count})={bias:+.4f}")
    results_dual[label] = float(weighted_bias)
    print(f"{label:12s} weighted bias: {weighted_bias:+.4f}   [{', '.join(detail)}]")

"""Gendered pairs (M/F, weighted average)"""

gendered_pairs = {
    "teacher": [("शिक्षक", word_counts["शिक्षक"]), ("शिक्षिका", word_counts["शिक्षिका"])],
    "writer": [("लेखक", word_counts["लेखक"]), ("लेखिका", word_counts["लेखिका"])],
    "student": [("छात्र", word_counts["छात्र"]), ("छात्रा", word_counts["छात्रा"]), ("विद्यार्थी", word_counts["विद्यार्थी"])],
    "actor": [("अभिनेता", word_counts["अभिनेता"]), ("अभिनेत्री", word_counts["अभिनेत्री"]), ("ऐक्टर", word_counts["ऐक्टर"])],
    "aide": [("सहायक", word_counts["सहायक"]), ("सहायिका", word_counts["सहायिका"])],
    "nurse": [("नर्स", word_counts["नर्स"]), ("परिचारक", word_counts["परिचारक"]), ("परिचारिका", word_counts["परिचारिका"])],
}

print("\n=== Gendered pairs (frequency-weighted average) ===")
results_gendered = {}
for label, forms in gendered_pairs.items():
    total_count = sum(count for _, count in forms)
    if total_count == 0:
        print(f"{label:12s} SKIPPED — zero total count")
        continue
    weighted_bias = 0
    detail = []
    for word, count in forms:
        bias = direct_bias(word, gender_direction, model)
        if bias is not None:
            weighted_bias += bias * (count / total_count)
            detail.append(f"{word}({count})={bias:+.4f}")
    results_gendered[label] = float(weighted_bias)
    print(f"{label:12s} weighted bias: {weighted_bias:+.4f}   [{', '.join(detail)}]")

print("\n=== Multi-word phrases (component-vector averaging) ===")

def multiword_vector(phrase_words, model):
    vecs = [model.wv[w] for w in phrase_words if w in model.wv]
    if not vecs:
        return None
    return np.mean(vecs, axis=0)

def direct_bias_vec(vec, gender_direction, c=1):
    cos_sim = cosine_sim(vec, gender_direction)
    return abs(cos_sim) ** c * np.sign(cos_sim)

# filmmaker
filmmaker_vec = multiword_vector(["फ़िल्म", "निर्माता"], model)
if filmmaker_vec is not None:
    bias_filmmaker = float(direct_bias_vec(filmmaker_vec, gender_direction))
    print(f"filmmaker: {bias_filmmaker:+.4f}")

# adventurer
adventurer_vec = multiword_vector(["साहसी", "यात्री"], model)
if adventurer_vec is not None:
    bias_adventurer = float(direct_bias_vec(adventurer_vec, gender_direction))
    print(f"adventurer: {bias_adventurer:+.4f}")

# astronaut
astronaut_vec = multiword_vector(["अंतरिक्ष", "यात्री"], model)
if astronaut_vec is not None:
    bias_astronaut = float(direct_bias_vec(astronaut_vec, gender_direction))
    print(f"astronaut: {bias_astronaut:+.4f}")

# comedian (M/F)
comedian_m_vec = multiword_vector(["हास्य", "अभिनेता"], model)
comedian_f_vec = multiword_vector(["हास्य", "अभिनेत्री"], model)
if comedian_m_vec is not None and comedian_f_vec is not None:
    bias_m = float(direct_bias_vec(comedian_m_vec, gender_direction))
    bias_f = float(direct_bias_vec(comedian_f_vec, gender_direction))
    count_m = full_text.count("हास्य अभिनेता")
    count_f = full_text.count("हास्य अभिनेत्री")
    total = count_m + count_f
    if total > 0:
        weighted_comedian = (bias_m * count_m + bias_f * count_f) / total
        print(f"comedian(M): {bias_m:+.4f}, comedian(F): {bias_f:+.4f}, weighted: {weighted_comedian:+.4f}")

"""Compile everything and get the final results"""

# Combine all results
all_results_hi = {}
all_results_hi.update(results_single)
all_results_hi.update(results_dual)
all_results_hi.update(results_gendered)
all_results_hi["filmmaker"] = -0.0481
all_results_hi["adventurer"] = -0.0060
all_results_hi["astronaut"] = 0.0017
all_results_hi["comedian"] = -0.1268

print(f"Total professions: {len(all_results_hi)}")

print("\n=== COMPLETE Hindi Profession Bias Ranking ===")
for label, bias in sorted(all_results_hi.items(), key=lambda x: x[1]):
    direction = "Female" if bias > 0 else "Male"
    print(f"{label:15s} {bias:+.4f}  ({direction})")

# Save to Drive
import json
with open(f"{DRIVE_DIR}/bias_scores.json", "w", encoding="utf-8") as f:
    json.dump(all_results_hi, f, ensure_ascii=False, indent=2)

# Corpus-level averages
simple_avg = sum(all_results_hi.values()) / len(all_results_hi)
print(f"\nSimple average: {simple_avg:+.4f}")

profession_word_map = {
    "scientist": ["वैज्ञानिक"], "musician": ["संगीतकार"], "artist": ["कलाकार"],
    "inventor": ["आविष्कारक"], "soldier": ["सैनिक"], "journalist": ["पत्रकार"],
    "athlete": ["खिलाड़ी"], "ambassador": ["राजदूत"], "analyst": ["विश्लेषक"],
    "lawyer": ["वकील"], "banker": ["बैंकर"], "biologist": ["जीवविज्ञानी"],
    "engineer": ["इंजीनियर", "अभियंता"], "manager": ["मैनेजर", "प्रबंधक"],
    "driver": ["ड्राइवर", "चालक"], "chef": ["शेफ", "रसोइया"],
    "judge": ["जज", "न्यायाधीश"], "governor": ["गवर्नर", "राज्यपाल"],
    "worker": ["मज़दूर", "कर्मचारी"], "farmer": ["किसान", "कृषक"],
    "person": ["व्यक्ति", "मनुष्य", "इंसान"], "astronomer": ["खगोलशास्त्री", "खगोलज्ञ"],
    "teacher": ["शिक्षक", "शिक्षिका"], "writer": ["लेखक", "लेखिका"],
    "student": ["छात्र", "छात्रा", "विद्यार्थी"], "actor": ["अभिनेता", "अभिनेत्री", "ऐक्टर"],
    "aide": ["सहायक", "सहायिका"], "nurse": ["नर्स", "परिचारक", "परिचारिका"],
}

profession_counts = {label: sum(word_counts[w] for w in words) for label, words in profession_word_map.items()}
profession_counts["filmmaker"] = full_text.count("फ़िल्म निर्माता")
profession_counts["adventurer"] = full_text.count("साहसी यात्री")
profession_counts["astronaut"] = full_text.count("अंतरिक्ष यात्री")
profession_counts["comedian"] = full_text.count("हास्य अभिनेता") + full_text.count("हास्य अभिनेत्री")

total = sum(profession_counts[l] for l in all_results_hi.keys())
weighted_avg = sum(all_results_hi[l] * profession_counts[l] for l in all_results_hi.keys()) / total
print(f"Weighted average: {weighted_avg:+.4f}")

final_summary_hi = {
    "simple_average": -0.0018,
    "weighted_average": -0.0117,
    "num_professions": 32,
    "gender_direction_pca_gap": 0.072,
    "corpus_articles": None,  # fill in your actual Hindi article count if known
}

with open(f"{DRIVE_DIR}/final_summary.json", "w", encoding="utf-8") as f:
    json.dump(final_summary_hi, f, ensure_ascii=False, indent=2)

print("Saved.")
print(json.dumps(final_summary_hi, indent=2))